# Generated by Django 4.2.16 on 2024-10-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp_threshold", models.FloatField(default=35.0)),
                (
                    "temperature_preference",
                    models.CharField(
                        choices=[
                            ("K", "Kelvin"),
                            ("C", "Celsius"),
                            ("F", "Fahrenheit"),
                        ],
                        default="CELSIUS",
                        max_length=1,
                    ),
                ),
                ("alert_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weather_condition", models.CharField(max_length=50)),
                ("temp", models.FloatField(default=0.0)),
                ("min_temp", models.FloatField(default=0.0)),
                ("max_temp", models.FloatField(default=0.0)),
                ("feels_like", models.FloatField(default=0.0)),
                ("dt", models.IntegerField(default=1729878673)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_updates",
                        to="weather_dashboard.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("avg_temp", models.FloatField(default=0.0)),
                ("max_temp", models.FloatField(default=0.0)),
                ("min_temp", models.FloatField(default=0.0)),
                ("dominant_weather", models.CharField(max_length=50)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to="weather_dashboard.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                ("threshold_value", models.FloatField()),
                ("is_triggered", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_dashboard.city",
                    ),
                ),
                (
                    "weather_update",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="weather_dashboard.weatherupdate",
                    ),
                ),
            ],
        ),
    ]
